### ISSUE TITLE
prompt=consent is required for scope offline_access

### ISSUE THREAD

**Issue by melanger** [UniversitaDellaCalabria/SATOSA-oidcop#1]
https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/blob/95c94f8ac0dfd94cb9970db9a724f859a12499fd/tests/test_oidcop.py#L398

Is this a standard thing or is it a choice of the oidcop library or this SATOSA frontend? I did not find it documented anywhere, and the error logs are not very helpful either. When I use the `offline_access` scope but do not include the `prompt` parameter at all, it does this:

```
[DEBUG]: - authorization_endpoint -
[INFO ]: Request: {'response_type': 'code', 'scope': 'openid profile email voperson_external_affiliation eduperson_entitlement offline_access', 'client_id': '...', 'redirect_uri': '...', 'state': '...', 'nonce': '...'}
[DEBUG]: authn_info: {}
[DEBUG]: {'response_type': 'code', 'scope': 'openid profile email voperson_external_affiliation eduperson_entitlement offline_access', 'client_id': '...', 'redirect_uri': '...', 'state': '...', 'nonce': '...'}, {'error': 'invalid_request', 'error_description': 'consent in prompt'}
[DEBUG]: [urn:uuid:...] Saved state in cookie SATOSA_STATE with properties [('expires', ''), ('path', '/'), ('comment', ''), ('domain', ''), ('max-age', ''), ('secure', True), ('httponly', ''), ('version', ''), ('samesite', 'None')]
[ERROR]: [urn:uuid:...] Uncaught exception
Traceback (most recent call last):
  File "/src/satosa/src/satosa/base.py", line 241, in run
    self._save_state(resp, context)
  File "/src/satosa/src/satosa/base.py", line 225, in _save_state
    resp.headers.append(tuple(cookie.output().split(": ", 1)))
AttributeError: 'dict' object has no attribute 'headers'
[ERROR]: Unknown error
Traceback (most recent call last):
  File "/src/satosa/src/satosa/base.py", line 241, in run
    self._save_state(resp, context)
  File "/src/satosa/src/satosa/base.py", line 225, in _save_state
    resp.headers.append(tuple(cookie.output().split(": ", 1)))
AttributeError: 'dict' object has no attribute 'headers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/satosa/src/satosa/proxy_server.py", line 148, in __call__
    resp = self.run(context)
  File "/src/satosa/src/satosa/base.py", line 258, in run
    raise SATOSAUnknownError("Unknown error") from err
satosa.exception.SATOSAUnknownError: Unknown error
```

When I add `prompt=consent`, the authentication works (even without a consent module).

**Comment by peppelinux** [comment]
Standing on the OAuth2/OIDC approach if a scope cannot be handled by an OP for a RP, it MUST be ignored.
So we have to handle this exception in a way to have a clear log message OP side (satosa) with a normal auth code response by OP, with offline_access omitted in the response.

@rohe introduced this check for the oidc certification of oidcop.
I'll take some days before back on this issue to finally patch satosa-oidcop and close it

**Comment by rohe** [comment]
So. based on https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.11
we should do the following for each bullet point.

"_MUST ensure that the prompt parameter contains consent unless other conditions for processing the request permitting offline access to the requested resources are in place; unless one or both of these conditions are fulfilled, then it MUST ignore the offline_access request,_"

Add a (configuration driven) method that permits/denies offline access whether or not consent appears in the prompt parameter.

"_MUST ignore the offline_access request unless the Client is using a response_type value that would result in an Authorization Code being returned,_"

Don't think we do this right now. Has to be added if missing.

"_MUST explicitly receive or have consent for all Clients when the registered application_type is web,_"
and
"_SHOULD explicitly receive or have consent for all Clients when the registered application_type is native._"

Not absolutely clear what is meant with '_all Clients_'.

**Comment by melanger** [comment]
> we can put this here https://github.com/IdentityPython/oidc-op/blob/master/docs/source/contents/faq.md
> 
> or here https://github.com/IdentityPython/oidc-op/blob/master/docs/source/contents/usage.md
> 
> would you like to give a pull request to oidcop with a proposal for this integration?

I created https://github.com/IdentityPython/oidc-op/pull/148, but I think it should be also mentioned in this repo, or at least link to oidc-op documentation.
