### ISSUE TITLE
Update dep to idpy-oidc

### ISSUE THREAD

**Issue by peppelinux** [UniversitaDellaCalabria/SATOSA-oidcop#13]
oidcop will not be mantained anymore, the development moevd to idpy-oidc

https://github.com/IdentityPython/idpy-oidc

that's for the next Minor release of satosa-oidcop (v0.7.0)

**Comment by melanger** [comment]
@peppelinux What is the status on this? Can I help? We need token exchange which is not implemented in oidc-op but it's in idpy-oidc.

**Comment by peppelinux** [comment]
Hi @melanger, Yes you can!

You find a branch where me and @MdreW started the migration from oidc-op to idpy-oidc, I think that the general configuration must be updated, we had a fault and I thought that's for this cause.

If you can do tests and give feedback we may do the work together.

Today it's a year of satosa-oidcop, in August 2021 i started developing It, It would be a very good birthday gift!

You can give us RealTime feedbacks also in idpy slack

**Comment by peppelinux** [comment]
The branch Is this
https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/tree/idpy-oidcop

**Comment by peppelinux** [comment]
now we have idpy-oidc v2.0.0
https://github.com/IdentityPython/idpy-oidc/releases/tag/v2.0.0

**Comment by peppelinux** [comment]
Migration completed in the PR below and read to your kindly revision :-)

https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/pull/36

the next release will be v2.0.0 if you agree
