### ISSUE TITLE
token refresh issues an unusable access token

### ISSUE THREAD

**Issue by melanger** [UniversitaDellaCalabria/SATOSA-oidcop#15]
related to https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/issues/5

# Steps to reproduce
Configuration: refresh token rotation enabled, mongoDB storage (dynamic client registration disabled)
```yaml
# ...
      authz:
        class: oidcop.authz.AuthzHandling
        kwargs:
          grant_config:
            expires_in: 43200 # 12 hours
# ...
        code:
          kwargs:
            lifetime: 300 # 5 minutes
        refresh:
          kwargs:
            lifetime: 2592000 # 1 month
        token:
          class: oidcop.token.jwt_token.JWTToken
          kwargs:
            lifetime: 3600 # 1 hour
# ...
```

I have setup the index for deletion as described [here](https://github.com/italia/Satosa-Saml2Spid/tree/master/mongo#create-expired-session-deletion).

1. Authenticate using authorization code flow with PKCE, prompt=consent and scope=offline_access, you obtain access token and refresh token
2. (at this point everything works as expected; access token works on introspection and userinfo, you can get a fresh access+refresh token using grant_type=refresh token on token endpoint and the new access token also works)
3. wait more than 1 hour but less than 12 hours
4. Refresh the tokens. The new access token (which is valid) cannot be used on userinfo or introspection.

# Current behavior

On userinfo, it returns:
```json
{"error": "invalid_request", "error_description": "Access not granted"}
```

Introspection crashes with an exception. The response is `Unknown error`, from logs:
```
[INFO ]: Cannot find "None" in client DB
[ERROR]: [urn:uuid:fe8299b0-a2ee-4923-aedb-7a6ae37fee9c] Uncaught exception
Traceback (most recent call last):
  File "/src/satosa/src/satosa/base.py", line 240, in run
    resp = self._run_bound_endpoint(context, spec)
  File "/src/satosa/src/satosa/base.py", line 180, in _run_bound_endpoint
    return spec(context)
  File "/opt/satosa/lib/python3.9/site-packages/satosa_oidcop/idpy_oidcop.py", line 459, in introspection_endpoint
    self._load_cdb(context)
  File "/opt/satosa/lib/python3.9/site-packages/satosa_oidcop/idpy_oidcop.py", line 105, in _load_cdb
    raise UnknownClient(client_id)
oidcop.exception.UnknownClient: None
[ERROR]: Unknown error
Traceback (most recent call last):
  File "/src/satosa/src/satosa/base.py", line 240, in run
    resp = self._run_bound_endpoint(context, spec)
  File "/src/satosa/src/satosa/base.py", line 180, in _run_bound_endpoint
    return spec(context)
  File "/opt/satosa/lib/python3.9/site-packages/satosa_oidcop/idpy_oidcop.py", line 459, in introspection_endpoint
    self._load_cdb(context)
  File "/opt/satosa/lib/python3.9/site-packages/satosa_oidcop/idpy_oidcop.py", line 105, in _load_cdb
    raise UnknownClient(client_id)
oidcop.exception.UnknownClient: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/satosa/src/satosa/proxy_server.py", line 148, in __call__
    resp = self.run(context)
  File "/src/satosa/src/satosa/base.py", line 258, in run
    raise SATOSAUnknownError("Unknown error") from err
satosa.exception.SATOSAUnknownError: Unknown error
```

# Expected behavior

The access token (which is valid) should work on userinfo and introspection the same way it works during the first hour.

**Comment by melanger** [comment]
I suspect that the "1 hour" is either the value `3600` from config (`token.kwargs.lifetime`) or it can be this:
https://github.com/IdentityPython/oidc-op/blob/fbc95ad60895bad0e4ef172ac948f54ad442c723/src/oidcop/authn_event.py#L7

**Comment by melanger** [comment]
@peppelinux Do you have any idea why this happens and how to prevent it? Or are you betting on https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/tree/idpy-oidcop?

**Comment by peppelinux** [comment]
@melanger it may depends by TTL of values on mongodb storage
we can have a pair session during a meeting to have a look at this

I'd moving this project to idpy, but as you can see we have the PR Grant Manager 2 in idpy that represent a huge breaking change, so I think that I'll wait until november before moving some step on the idpy branch

I'm really interested in your envolvment in this project, so we can have some pair session if you agree

**Comment by melanger** [comment]
I guess this was specific to our setup
