### ISSUE TITLE
Sub_type pairwise cannot be selected

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [UniversitaDellaCalabria/SATOSA-oidcop#21]
Hi,

This is partly a follow-up to #20.

I see the OidcOpFrontend module is meant to support pairwise `sub_type`, but this cannot really be selected.

In `oidcop/session/manager.py`, `create_session` has `sub_type` defaulting to `public`, but when OidcOpFrontend calls `create_session`, it does not pass a value for `sub_type`, so `public` is always used as the default.

I'd think that if a client has include `subject_type` in its registration, the value passed under `subject_type` should be used for the `sub_type` argument to `create_session` - that would solve this issue.

Thanks a lot in advance for considering it.

Cheers,
Vlad

**Comment by peppelinux** [comment]
Ok, you mean here
https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/blob/main/satosa_oidcop/idpy_oidcop.py#L637

I'm ok with this proposal, if we don't have any cons we can proceed with a PR if you agree @vladimir-mencl-eresearch
