### ISSUE TITLE
Scope response from /token

### ISSUE THREAD

**Issue by ar-filho** [UniversitaDellaCalabria/SATOSA-oidcop#29]
The response of the “scope” attribute presented by the /token endpoint is in string array format. Based on the rfc https://www.rfc-editor.org/rfc/rfc6749#section-3.3 “the value of the scope parameter is expressed as a list of space-delimited, case-sensitive strings”. This same orientation is used for the other endpoints.

**Comment by peppelinux** [comment]
Please share here the json object that represent the token endpoint response, then we'll focus on the parameter value to fixed with a PR

thank you @ar-filho

**Comment by ar-filho** [comment]
```
HTTP/1.1 200
Content-Type: application/json
{
  "token_type": "Bearer",
  "scope": [
    "openid",
    "profile",
    "email"
  ],
  "access_token": "eyJhbGciOiJFUzI1NiIs...",
  "expires_in": 1800,
  "id_token": "eyJhbGciOiJFUzI1NiIs...",
}

```
Should be:
```
HTTP/1.1 200
Content-Type: application/json
{
  "token_type": "Bearer",
  "scope": "openid profile email",
  "access_token": "eyJhbGciOiJFUzI1NiIs...",
  "expires_in": 1800,
  "id_token": "eyJhbGciOiJFUzI1NiIs...",
}

```

Systems like keycloak (java, strongly typed) demand the return of variables according to rfc.

*_Removed the complete token information._

**Comment by peppelinux** [comment]
I'll back to you soon with a patch and a brand new release, thank you for having reached us with this issue

**Comment by ar-filho** [comment]
The change worked for this endpoint /token.
Check if the token payload would need to be in this format.

**Comment by peppelinux** [comment]
I assume that also the AT should have the scope as a string

@rohe

**Comment by rohe** [comment]
Yes! If it follows RFC9068.

**Comment by peppelinux** [comment]
@rohe do we need a patch in idpy-oidc as well?

I say idpy-oidc because I believe that oidcop support is discontinued, so for satosa-oidcop I just need to put patches untill the migration to idpy-oidc is done

**Comment by rohe** [comment]
Turns out JWTToken, the class that produces access tokens as signed JWTs aren't following RFC9068 so I have to fix that.
That the access token response on the other hand is incorrect is a surprise to me. Have to look into that.

**Comment by rohe** [comment]
My first simple test says that idly-oidc does the right thing and that scope is returned as space separated list of items and not as a list. Will do some more testing after a set of meetings coming up now.

**Comment by peppelinux** [comment]
This issue is resolevd by release v1.1.1 but this discussion is still open due to some pending checks related to the next migration to idpy-oidc

**Comment by peppelinux** [comment]
@ar-filho do you have solved this issue?

**Comment by ar-filho** [comment]
This issue has been resolved.
