### ISSUE TITLE
unusable access tokens

### ISSUE THREAD

**Issue by melanger** [UniversitaDellaCalabria/SATOSA-oidcop#5]
I discovered that with a static mongodb client configuration, the access tokens are in some cases unusable on introspection and/or userinfo endpoint. I thought the problem was https://github.com/IdentityPython/oidc-op/issues/141 but actually it depends on grant type. The situation for me is this:

* implicit flow (`response_type=token`) results in a token which cannot be used on any endpoint (introspection nor userinfo)
* authorization code flow (`response_type=code`) results in a valid token, but after restarting SATOSA it later cannot be used on introspection endpoint (userinfo works)

With implicit flow, the error is:

```
{"error": "invalid_request", "error_description": "request cannot be processed"}
```

With authorization code flow, after SATOSA restart, introspection endpoint returns:

```
{"error": "unauthorized_client", "error_description": "Authorization failed"}
```

Both cases fail with errors about client database being empty (see https://github.com/IdentityPython/oidc-op/issues/141 for more details).

The result is that only authorization code flow works and I cannot restart a running instance. I suspect that the restart error might be caused by an auto-generated salt or key, but I fixed all documented configuration options with salts and key to static values.

**Comment by melanger** [comment]
Deleted session storage (`db.session.remove({})`), restarted SATOSA.
- [x] authz code + userinfo
- [x] authz code + introspection
- [x] implicit + userinfo
- [x] implicit + introspection

Restarted SATOSA (without removing session data)

- [x] old token from authz code + userinfo
- [x] old token from authz code + introspection
- [x] old token from implicit + userinfo
- [x] old token from implicit + introspection
- [x] new token from authz code + userinfo
- [x] new token from authz code + introspection
- [x] new token from implicit + userinfo
- [x] new token from implicit + introspection

All looks good!

Notes:
- the `sub` claim inside access token contains the `client_id`, not the `sub` of the user, although both userinfo and introspection endpoint return user ID in the `sub` property. The id_token also contains the user ID in the sub claim. I guess the point is that access token [should be an opaque string](https://datatracker.ietf.org/doc/html/rfc6749#section-1.4), but I believe some client libraries try to read claims from the access token as well, which might result in errors (all users would get the same user ID). Can this be configured?
- trying to use the introspection endpoint without authentication results in server-side error `Uncaught exception: oidcop.exception.InvalidClient: Client None not found!`

**Comment by peppelinux** [comment]
Great to hear this! I'm going to close this issue.

regarding your notes:

1. The, in auth code flow the access token have been released to the RP and not to the user, so the subject is the RP. Please check this in implicit flow as well, if you get something different we'll take a look into oidcop

2. Yes, the id token have been issued to the user. The access token won't identify the user but you can also add whatever claims in access token using oidcop general configuration. Or, also, you can configure the introspection endpoint to give additional cliams, also related to the user, for a sumbitted access token

3. the access token is JWS, didn't get what you would to do to prevent collisions of meaning, client side, tell me more but in oidcop issues and not here if you agree.

4. mmhhh ... yes, I'd prefer to have a trust relation with the consumer of introspection endpoint, but something that can be configured in your provider configuration. See this https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/blob/6731989dad5e95d862f0312b6ef2dad92544788b/example/oidcop_frontend.yaml#L129. In our example this endpoint is protected by some client authenticatins, feel free to change at your taste, but in your project. I believe that the example configuration would be good enough for a quite common provider.

**Comment by melanger** [comment]
OK, I understand the difference between `sub` in access token and other places, it makes sense.

ad 4. I also have authentication in place, but if someone ("attacker" or unskilled user) tries it without authentication, it raises an uncaught exception. I suppose the exception should be caught and the endpoint should return a proper error response.

There is also a difference between responses from userinfo and introspection when an expired token is used.

Userinfo: `{"error": "invalid_token", "error_description": "Invalid Token"}`
Introspection: `{"error": "invalid_request", "error_description": "request cannot be processed"}`
