### ISSUE TITLE
Error in Chrome and Edge browsers

### ISSUE THREAD

**Issue by ar-filho** [UniversitaDellaCalabria/SATOSA-oidcop#52]
I'm having problems using Satosa(v8.4.0)+OidcOp(v3.0.3) on Chrome and Edge browsers. In these browsers, after authentication and registration of the session in the database, Satosa shows `[CRITICAL] WORKER TIMEOUT (pid:10)` and restarts and does not allow the authentication and authorization flow, as Oidcop does not find the session.

I evaluated Satosa's new cookie configuration options in version 8.4.0 and was unsuccessful.
In Satosa(v8.4.0)+OidcOp(v2.0.1) it also occurs.

In the Mozilla Firefox browser, the error does not occur, and the flow completes successfully.

**Comment by peppelinux** [comment]
does your deployment work on HTTPs or HTTP?

**Comment by peppelinux** [comment]
it seems a configuration error.

**Comment by ar-filho** [comment]
Works over https.
However, the error does not occur in Firefox.

**Comment by melanger** [comment]
Chrome starting blocking third party cookies for some users in 2024, maybe it might be related? Do you set "SameSite=None" on your cookies?

**Comment by ar-filho** [comment]
> Chrome starting blocking third party cookies for some users in 2024, maybe it might be related? Do you set "SameSite=None" on your cookies?

I used this option too, and the error continues.

\
\
After authenticating to SAML, OIDCOP saves different values for cookies in the
`idpyoidc.server.oauth2.authorization.authz_part2:1025 resp_info`. The stored values differ from the values chosen in `proxy_conf.yaml`.

In the plugin settings, for Satosa, the `cookie_handler` options are commented out. Uncommenting these lines, even if we are not going to use logout, and defining them equal to `proxy_conf.yaml`, the values are correct for the database but it also does not solve the problem.

Satosa breaks after:
```
[satosa.state.state_to_cookie:176] [urn:uuid:xxxomittedxxx] Saved state in cookie SATOSA_STATE with properties [('expires', ''), ('path', '/'), ('comment', '' ), ('domain', ''), ('max-age', 0), ('secure', True), ('httponly', False), ('version', ''), ('samesite' , 'None')]
```

**Comment by peppelinux** [comment]
hint: httponly should be set to True

if you open the debug basr of your user-agent and inspect the http requests/responses, can you see the cookie passed?

when you say:
> The stored values differ from the values chosen in proxy_conf.yaml.

when the cookies changes? when the error occours, after the user authentication,. in the frontend callback or in the backend?

any information is important

**Comment by ar-filho** [comment]
> hint: httponly should be set to True

This configuration was tested and did not work.
<br/><br/>

> if you open the debug basr of your user-agent and inspect the http requests/responses, can you see the cookie passed?

Yes. Checking Chrome's memory inspection, at the address where SATOSA is located, we have the cookie created before passing it on to the DS.
The Cookie remains until the SAML assertion returns, to be sent to Satosa's SAML backend. After this round, the cookie is consumed and deleted. According to proxy_conf.yaml configuration (`CONTEXT_STATE_DELETE: True`).
<br/><br/>

> when you say:
> 
> > The stored values differ from the values chosen in proxy_conf.yaml.

In the Satosa debug log, it shows the message in the request step received by OIDCOP at `[idpyoidc.server.oauth2.authorization.authz_part2:1025]`. The values of `resp_info: 'response_args'` of `idpyoidc.message.oidc.AuthorizationResponse` and the cookie-related fields are different.

To keep the same as those configured in `proxy_conf.yaml` I used the OIDCOP configuration directives from `cookie_handle`. However, it did not solve the problem.
<br/><br/>

> when the cookies changes? when the error occours, after the user authentication,. in the frontend callback or in the backend?
> any information is important

Cookies have not changed. Only OIDCOP logs values different from those configured in `proxy_conf.yaml`. I don't know if this impacts the error.

The flow occurs normally. Frontend-Oidcop receives the Authorization Code request. Satosa sends to Backend-SAML. I authenticate in Saml IdP. SAML Assertion returns to Backend-SAML. Satosa performs all micro-services processes and sends them to Frontend-Oidcop. Frontend-Oidcop registers in the DB, creates the Authorization Code and passes it on to the Relying Party (RP). After that, the cookie is consumed in the browser. The RP receives the Authorization Code, but Satosa presents a critical error `[1] [CRITICAL] WORKER TIMEOUT (pid:10)`.
Afterwards, Satosa restarts, but no longer finds the Session, and the RP cannot access the Token Endpoint.

**Comment by peppelinux** [comment]
ok, from your analysis it seems to me that cookie is not the problem but `[1] [CRITICAL] WORKER TIMEOUT (pid:10)` you have a sort of problem with socket/processes

do you use docker?
how many worker do you have configured?
the mongodb is in the same host or different host?

configuration of the connection, like socket timeout on the mongodb server, might result in anomalies that then produces worker timeout/harakiri

**Comment by ar-filho** [comment]
> ok, from your analysis it seems to me that cookie is not the problem but `[1] [CRITICAL] WORKER TIMEOUT (pid:10)` you have a sort of problem with socket/processes
> 
> do you use docker? how many worker do you have configured? the mongodb is in the same host or different host?

I use docker. Docker only has one worker. Mongodb and satosa are in the same composition (docker_compose on the same host), so they are on the same internal docker network, but with different addresses (see the inspect below). In the OIDCOP plugin configuration I am using the name `mongo` which is also in mongodb's `dnsnames`.

<br/><br/>

> configuration of the connection, like socket timeout on the mongodb server, might result in anomalies that then produces worker timeout/harakiri

Our mongo has the default docker deployment settings. And reinforcing, it works normally in Firefox and Chrome's incognito tab.

<br/><br/>

Network, from commands (docker inspect mongo / docker inspect satosa):
```
Mongodb:
"Networks": {
    "satosa-docker_default": {
        "IPAMConfig": null,
        "Links": null,
        "Aliases": [
            "mongo",
            "45fe925a87d2"
        ],
        "MacAddress": "02:42:ac:13:00:02",
        "NetworkID": "c3fbdde3a90107bb4c0dcac8108bf7fe05a9445bbf5e13fa09f2d201ca51a82e",
        "EndpointID": "2d6b6fe7950f3f66c543f40f0f41bb5ba27e0cef4770c5a9478aff1757ab1d97",
        "Gateway": "172.19.0.1",
        "IPAddress": "172.19.0.2",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "DriverOpts": null,
        "DNSNames": [
            "mongo",
            "45fe925a87d2"
        ]
    }

Satosa:
"Networks": {
    "satosa-docker_default": {
        "IPAMConfig": null,
        "Links": null,
        "Aliases": [
            "satosa",
            "e6ceaccaf811"
        ],
        "MacAddress": "02:42:ac:13:00:03",
        "NetworkID": "c3fbdde3a90107bb4c0dcac8108bf7fe05a9445bbf5e13fa09f2d201ca51a82e",
        "EndpointID": "f7c3c6afb2064babc8711266d645edfe001f9da3ee2aec9f62980f42b4bdce7e",
        "Gateway": "172.19.0.1",
        "IPAddress": "172.19.0.3",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "DriverOpts": null,
        "DNSNames": [
            "satosa",
            "e6ceaccaf811"
        ]
    }
```

**Comment by ar-filho** [comment]
​The Issue problem persists.
We've found that Satosa + OIDCOP works on Mozilla Firefox, Chrome (Incognito), and Edge (InPrivate). But it doesn't work on Chrome and Edge in the regular tab.

We conducted tests using the RP of the OIDC Playground (https://openidconnect.net/) and RP SimpleSamlPhp. We could test other RPs, but the problem remained the same with these two different RPs. We continued the tests using the OIDC Playground.

We conducted tests by clearing all cookies and cache from Chrome and Edge browsers. Nevertheless, the issue persists, not working in the regular tab but working in the incognito tab.

We removed the use of our Discovery Service(DS) to reduce the cookie forwarding from it. However, the error persists. We continued the tests without using the DS.

We performed several debugs on the plugin, Satosa, and even Gunicorn. The requests made by browsers are different in each model (Firefox, Chrome, and Edge). So we compared Chrome in the regular tab with Chrome in the incognito tab.

We used debugging at two different moments but following the same authentication and authorization flow:

    1- satosa/proxy_server.py(69)unpack_request() 
    1.1- RP -> FrontendOIDCOP
    
    2- satosa/proxy_server.py(110)__call__() 
    2.1- BackendSAML -> IDP
    
    3- satosa/proxy_server.py(69)unpack_request()
    3.1- IDP -> BackendSAML
    
    4- satosa/proxy_server.py(110)__call__()
    4.1- FrontendOIDCOP -> RP
    
Analyzing the debugs, we found that the __call__() function in Chrome's incognito tab uses a different "Arbiter(self).run()":

    /usr/local/lib/python3.12/site-packages/gunicorn/arbiter.py(211)run()
While the regular tab uses:

    /usr/local/lib/python3.12/site-packages/gunicorn/arbiter.py(202)run()
    
The "environ" variables of these functions differ in: "gunicorn.http.wsgi" object, "laddr" port, "HTTP_ACCEPT_LANGUAGE", "REMOTE_PORT", "HTTP_COOKIE".

`HTTP_ACCEPT_LANGUAGE` I tested forcing the use of only English or Portuguese in the browser, and the problem persisted.

We need help with this demand. I can send the debug files.
Could you guide us where else we should analyze this problem?
We need to know if the problem is in the plugin, or if it's in satosa, or if it's in gunicorn.
Could you inform us if anyone else has had similar problems?

**Comment by peppelinux** [comment]
please use uwsgi using as configuraiton example the base shared in satosa-saml2spid and report here if possible if the problem persists

**Comment by ar-filho** [comment]
We were able to resolve the issue using SATOSA + OIDCOP + UWSGI + NGINX in docker.

The current version of Satosa-Oidcop uses the `idpyoidc` library in version 2.1.0. `idpyoidc` needs `cryptojwt` in version >=1.8.1, but pip installs the latest version, 1.9.0 (release Apr 11, 2024). This version has new algorithms (‘EdDSA’, ‘Ed25519’, ‘Ed448’) and these algorithms cause errors in `idpyoidc`. To resolve this, it was necessary to set the version of `cryptojwt` to 1.8.1 before installing Satosa-Oidcop.

We could suggest that `idpyoidc` in version 2.1.0, leave `cryptojwt` in `>=1.8.1,<1.8.3` as a requirement.

Thank everyone for their attention, especially @peppelinux .
