### ISSUE TITLE
[prompt=consent for scope offline_access] 'dict' object has no attribute 'headers'

### ISSUE THREAD

**Issue by melanger** [UniversitaDellaCalabria/SATOSA-oidcop#7]
I am getting a strange uncaught exception from SATOSA:

```
Uncaught exception
Traceback (most recent call last):
  File "/src/satosa/src/satosa/base.py", line 241, in run
    self._save_state(resp, context)
  File "/src/satosa/src/satosa/base.py", line 225, in _save_state
    resp.headers.append(tuple(cookie.output().split(": ", 1)))
AttributeError: 'dict' object has no attribute 'headers'

[ERROR]: Unknown error
Traceback (most recent call last):
  File "/src/satosa/src/satosa/base.py", line 241, in run
    self._save_state(resp, context)
  File "/src/satosa/src/satosa/base.py", line 225, in _save_state
    resp.headers.append(tuple(cookie.output().split(": ", 1)))
AttributeError: 'dict' object has no attribute 'headers'

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/src/satosa/src/satosa/proxy_server.py", line 148, in __call__
    resp = self.run(context)
  File "/src/satosa/src/satosa/base.py", line 258, in run
    raise SATOSAUnknownError("Unknown error") from err
satosa.exception.SATOSAUnknownError: Unknown error
```

It happens when somebody requests scope `offline_access` without `prompt=consent` and the authorization endpoint is trying to return an error with the message `"consent in prompt"`, also with other errors. The problem might be with this line:

https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/blob/554273a4757c5584120d3a9686c07e7054b6bd38/satosa_oidcop/idpy_oidcop.py#L539

It returns a plain dictionary (literally `{'error': 'invalid_request', 'error_description': 'consent in prompt'}`) which is passed all the way here:

https://github.com/IdentityPython/SATOSA/blob/003881baffcd26ae2e4e3d89ba74184a7175fa4b/src/satosa/base.py#L225

where a Response object is expected, hence the error.

**Comment by peppelinux** [comment]
Yes, it's up to oidcop here
https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/issues/1#issuecomment-956280923

**Comment by peppelinux** [comment]
during the next days we'll have another release of oidcop, probably we'll see this issues after that
tests are necessary

**Comment by peppelinux** [comment]
@melanger @rohe
Ok I think that oidcop handles well the client authorization (yes, it must deny standing to official oidc rules)

and that satosa-oidcop should set a dummy cookie to prevent that SATOSABase. _save_state method raises this exception
so I think that I have to stydu a workaround after getting some suggestion from other satosa developers about the best practice to adopt for this workaround

**Comment by peppelinux** [comment]
@melanger found a way, I'll do a patch and a following release asap

**Comment by peppelinux** [comment]
done @melagener
https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/releases/tag/v0.4.7

your feedback is always appreciated
